export const BROWSER_FILTER_SEARCH_REQUEST = 'BROWSER_FILTER_SEARCH_REQUEST'
export const BROWSER_FILTER_SEARCH_SUCCESS = 'BROWSER_FILTER_SEARCH_SUCCESS,'
export const BROWSER_FILTER_SEARCH_FAIL = 'BROWSER_FILTER_SEARCH_FAIL'

export const BROWSER_SEARCH_REQUEST = 'BROWSER_SEARCH_REQUEST'
export const BROWSER_SEARCH_SUCCESS= 'BROWSER_SEARCH_SUCCESS'
export const BROWSER_SEARCH_FAIL = 'BROWSER_SEARCH_FAIL'

export const BROWSER_FETCH_PRODUCTS_REQUEST = 'BROWSER_FETCH_PRODUCTS_REQUEST'
export const BROWSER_FETCH_PRODUCTS_SUCCESS = 'BROWSER_FETCH_PRODUCTS_SUCCESS'
export const BROWSER_FETCH_PRODUCTS_FAIL = 'BROWSER_FETCH_PRODUCTS_FAIL'


