export const BROWSER_SEARCHREQUEST = 'BROWSER_SEARCHREQUEST'
export const BROWSER_SEARCHSUCCESS = 'BROWSER_SEARCHSUCCESS'
export const BROWSER_FAIL = 'BROWSER_FAIL'

export const BROWSER_TAB_REQUEST = 'BROWSER_TAB_REQUEST'
export const BROWSER_TAB_SUCCESS = 'BROWSER_TAB_SUCCESS'
export const BROWSER_TAB__FAIL = 'BROWSER_TAB__FAIL'
