export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_ALL_TOP_REQUEST = 'PRODUCT_ALL_TOP_REQUEST'
export const PRODUCT_ALL_TOP_SUCCESS = 'PRODUCT_ALL_TOP_SUCCESS'
export const PRODUCT_ALL_TOP_FAIL = 'PRODUCT_ALL_TOP_FAIL'

export const PRODUCT_SPECIAL_REQUEST = 'PRODUCT_SPECIAL_REQUEST'
export const PRODUCT_SPECIAL_SUCCESS = 'PRODUCT_SPECIAL_SUCCESS'
export const PRODUCT_SPECIAL_FAIL = 'PRODUCT_SPECIAL_FAIL'

export const HOME_DATA_REQUEST = 'HOME_DATA_REQUEST'
export const HOME_DATA_SUCCESS = 'HOME_DATA_SUCCESS'
export const HOME_DATA_FAIL = 'HOME_DATA_FAIL'

export const DROPDOWN_REQUEST = ' DROPDOWN_REQUEST'
export const DROPDOWN_SUCCESS = 'DROPDOWN_SUCCESS'
export const DROPDOWN_FAIL = 'DROPDOWN_FAIL'
