export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_ALL_TOP_REQUEST = 'PRODUCT_ALL_TOP_REQUEST'
export const PRODUCT_ALL_TOP_SUCCESS = 'PRODUCT_ALL_TOP_SUCCESS'
export const PRODUCT_ALL_TOP_FAIL = 'PRODUCT_ALL_TOP_FAIL'

export const PRODUCT_SALE_REQUEST = 'PRODUCT_SALE_REQUEST'
export const PRODUCT_SALE_SUCCESS = 'PRODUCT_SALE_SUCCESS'
export const PRODUCT_SALE_FAIL = 'PRODUCT_SALE_FAIL'

export const BANNER_ADD_REQUEST = 'BANNER_ADD_REQUEST'
export const BANNER_ADD_SUCCESS = 'BANNER_ADD_SUCCESS'
export const BANNER_ADD_FAIL = 'BANNER_ADD_FAIL'

export const DROPDOWN_REQUEST = ' DROPDOWN_REQUEST'
export const DROPDOWN_SUCCESS = 'DROPDOWN_SUCCESS'
export const DROPDOWN_FAIL = 'DROPDOWN_FAIL'
